C:\Python34\OZprojects\DYESOPT\DYESOPT\DynSim&TEcalculations\ResFuel\HES3_1__TES0__EEG1_2__EES0\model\HES3_1__TES0__EEG1_2__EES0.dck
C:\Trnsys17\MyProjects\OZexecTrial3\SDHW-TRNSED (Studio).trd
C:\Osama\TRNExecutable\TRNSED_App\CHP_RES_FUELmodel\HES3_1__TES0__EEG1_2__EES0.tpf
C:\Osama\TRNExecutable\TRNSED_App\CHP_RES_FUELmodel\trd\HES3_1__TES0__EEG1_2__EES0.TRD
C:\Osama\TRNExecutable\TRNSED_App\CHP_RES_FUELmodel\HES3_1__TES0__EEG1_2__EES0.dck
C:\OSAMA\TRNEXECUTABLE\TRNSED_APP\CHP_RES_FUELMODEL\HES3_1__TES0__EEG1_2__EES0.TRD
C:\PYTHON34\OZPROJECTS\DYESOPT\DYESOPT\DYNSIM&TECALCULATIONS\RESFUEL\HES3_1__TES0__EEG1_2__EES0\MODEL\HES3_1__TES0__EEG1_2__EES0.TRD
C:\DYESOPT\DYESOPT\DYNSIM&TECALCULATIONS\RESFUEL\HES3_1__TES0__EEG1_2__EES0\MODEL\HES3_1__TES0__EEG1_2__EES0.TRD
