import importlib
from decimal import Decimal

IC        = importlib.import_module('DynSim&TEcalculations.ResFuel.HES3_1__TES0__EEG1_2__EES0.technoEconomics.calculateInvestmentCost' )
OMC       = importlib.import_module('DynSim&TEcalculations.ResFuel.HES3_1__TES0__EEG1_2__EES0.technoEconomics.calculateOperationMaintenanceCost' )
CompPower = importlib.import_module('DynSim&TEcalculations.ResFuel.HES3_1__TES0__EEG1_2__EES0.output.calculateComponentPower')
PerfNo_FIN= importlib.import_module('DynSim&TEcalculations.ResFuel.HES3_1__TES0__EEG1_2__EES0.technoEconomics.calculatePerformance_noFIN')
print(' ')
print(' ')
print(' ')
print(' POWER PLANT PERFORMANCE: ')
print(' ')
print('  CAPEX Results   ----------------------------------------------- ')
print(' ')
print(' Total Investment Cost:        ' +  str(round(Decimal(IC.result_cost_CAPEXtot/1e6),2)) + '   [milUSD]' )
print(' ')
# print('	Direct Investment: ')
# print('Steam turbogenerator set:        %6.1f [milUSD]\n' +   str(result_cost_CAPEX_STG_Cost/1e6))
# print('Condenser and cooling tower:     %6.1f [milUSD]\n' +   str(result_cost_CAPEX_Condenser_Cost/1e6))
print('  OPEX Results   ------------------------------------------------ ')
print(' ')
print(' Total Annual OPEX:            ' +  str(round(Decimal(OMC.result_cost_OPEXtot/1e6),2)) + '     [milUSD/yr]' )
print(' ')
print('  Power Production Results   ------------------------------------ ')
print(' ')
print(' Net Electricity Production:   ' +  str(round(Decimal(CompPower.result_plant_Etot/1000),2)) + '     [GWhe/yr]' )
# print(1,' Net Electricity HPT:            %6.2f [GWhe/yr]\n',  result_plant_Etot/1000)
# print(1,' Net Electricity LPT:            %6.2f [GWhe/yr]\n',  result_plant_Etot/1000)
print(' Gross Electricity Production: ' +  str(round(Decimal(CompPower.result_plant_Egross_tot/1000),2)) + '     [GWhe/yr]' )
print(' Parasitic Consumption:        ' +  str(round(Decimal(CompPower.result_plant_Epar_tot/1000),2)) + '     [GWhe/yr]')
print(' Fuel Consumption:             ' +  str(round(Decimal(CompPower.result_plant_FUEL_tot),2)) + '  [ton/yr]')
print(' ')
print(' Condenser Pump Parasitic:     ' +  str(round(Decimal(CompPower.result_plant_Epar_P1/1000),2)) + '     [GWhe/yr]')
print(' Deaerator Pump Parasitic:     ' +  str(round(Decimal(CompPower.result_plant_Epar_P2/1000),2)) + '     [GWhe/yr]')
print(' ')
print(' ')
print('  Economic Performance   ---------------------------------------- ')
print(' ')
print(' LCOE:                         ' +  str(round(Decimal(PerfNo_FIN.result_econ_CHP_LCOE),2)) + '  [USD/MWhe]')
print(' Capacity factor:              ' +  str(round(Decimal(PerfNo_FIN.result_econ_cf_el*100),2)) + '     [%]')


