networks:
  simulation:
    driver: bridge
services:
  base0:
    build:
      context: base0
      dockerfile: Dockerfile_base
    command: wrapper_base.py Base0 GRP0
    container_name: base0
    depends_on:
    - orch
    environment:
      ZMQ_PUSH_ADDRESS: tcp://orch:5557
      ZMQ_SUB_ADDRESS: tcp://orch:5556
    networks:
    - simulation
    volumes:
    - .\base0:/code
  orch:
    build:
      context: orch
      dockerfile: Dockerfile
    command: orch.py
    container_name: orch
    networks:
    - simulation
    ports:
    - 5556:5556
    - 5557:5557
    volumes:
    - .\orch:/code
version: '3'
